version: '3.9'
services:
  mysqldb:
    image: mysql
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$DB_PASSWORD
      - MYSQL_DATABASE=$DB_NAME
    ports:
      - $DB_PORT:$DB_PORT
  app:
    build: .
    depends_on:
      - mysqldb
    links:
      - mysqldb
    ports:
      - $PORT:$PORT
    
